//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace OpenTheWindows.App.Resources;

using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Strings
{

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Strings()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenTheWindows.App.Resources.Strings", typeof(Strings).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly-typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    /// <summary>Looks up a localized string similar to Yes.</summary>
    internal static string Common_Yes
    {
        get
        {
            return ResourceManager.GetString("Common_Yes", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to No.</summary>
    internal static string Common_No
    {
        get
        {
            return ResourceManager.GetString("Common_No", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Apply.</summary>
    internal static string Common_Apply
    {
        get
        {
            return ResourceManager.GetString("Common_Apply", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Cancel.</summary>
    internal static string Common_Cancel
    {
        get
        {
            return ResourceManager.GetString("Common_Cancel", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Revert.</summary>
    internal static string Common_Revert
    {
        get
        {
            return ResourceManager.GetString("Common_Revert", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Refresh.</summary>
    internal static string Common_Refresh
    {
        get
        {
            return ResourceManager.GetString("Common_Refresh", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Search.</summary>
    internal static string Common_Search
    {
        get
        {
            return ResourceManager.GetString("Common_Search", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Close.</summary>
    internal static string Common_Close
    {
        get
        {
            return ResourceManager.GetString("Common_Close", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to OK.</summary>
    internal static string Common_Ok
    {
        get
        {
            return ResourceManager.GetString("Common_Ok", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Dashboard.</summary>
    internal static string Nav_Dashboard
    {
        get
        {
            return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Privacy.</summary>
    internal static string Nav_Privacy
    {
        get
        {
            return ResourceManager.GetString("Nav_Privacy", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Updates.</summary>
    internal static string Nav_Updates
    {
        get
        {
            return ResourceManager.GetString("Nav_Updates", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Security.</summary>
    internal static string Nav_Security
    {
        get
        {
            return ResourceManager.GetString("Nav_Security", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Performance.</summary>
    internal static string Nav_Performance
    {
        get
        {
            return ResourceManager.GetString("Nav_Performance", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Debloat.</summary>
    internal static string Nav_Debloat
    {
        get
        {
            return ResourceManager.GetString("Nav_Debloat", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Shell.</summary>
    internal static string Nav_Shell
    {
        get
        {
            return ResourceManager.GetString("Nav_Shell", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Profiles.</summary>
    internal static string Nav_Profiles
    {
        get
        {
            return ResourceManager.GetString("Nav_Profiles", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to History.</summary>
    internal static string Nav_History
    {
        get
        {
            return ResourceManager.GetString("Nav_History", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Settings.</summary>
    internal static string Nav_Settings
    {
        get
        {
            return ResourceManager.GetString("Nav_Settings", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to About.</summary>
    internal static string Nav_About
    {
        get
        {
            return ResourceManager.GetString("Nav_About", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Safe.</summary>
    internal static string Risk_Safe
    {
        get
        {
            return ResourceManager.GetString("Risk_Safe", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Caution.</summary>
    internal static string Risk_Caution
    {
        get
        {
            return ResourceManager.GetString("Risk_Caution", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Advanced.</summary>
    internal static string Risk_Advanced
    {
        get
        {
            return ResourceManager.GetString("Risk_Advanced", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Breaking.</summary>
    internal static string Risk_Breaking
    {
        get
        {
            return ResourceManager.GetString("Risk_Breaking", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Off.</summary>
    internal static string Level_Off
    {
        get
        {
            return ResourceManager.GetString("Level_Off", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Basic.</summary>
    internal static string Level_Basic
    {
        get
        {
            return ResourceManager.GetString("Level_Basic", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Balanced.</summary>
    internal static string Level_Balanced
    {
        get
        {
            return ResourceManager.GetString("Level_Balanced", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Strict.</summary>
    internal static string Level_Strict
    {
        get
        {
            return ResourceManager.GetString("Level_Strict", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Paranoid.</summary>
    internal static string Level_Paranoid
    {
        get
        {
            return ResourceManager.GetString("Level_Paranoid", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to No restart.</summary>
    internal static string Restart_None
    {
        get
        {
            return ResourceManager.GetString("Restart_None", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Restart Explorer.</summary>
    internal static string Restart_ExplorerRestart
    {
        get
        {
            return ResourceManager.GetString("Restart_ExplorerRestart", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Sign out.</summary>
    internal static string Restart_SignOut
    {
        get
        {
            return ResourceManager.GetString("Restart_SignOut", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Reboot.</summary>
    internal static string Restart_Reboot
    {
        get
        {
            return ResourceManager.GetString("Restart_Reboot", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Draft.</summary>
    internal static string Status_Draft
    {
        get
        {
            return ResourceManager.GetString("Status_Draft", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Verified.</summary>
    internal static string Status_Verified
    {
        get
        {
            return ResourceManager.GetString("Status_Verified", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Deprecated.</summary>
    internal static string Status_Deprecated
    {
        get
        {
            return ResourceManager.GetString("Status_Deprecated", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to All risks.</summary>
    internal static string Filter_AllRisks
    {
        get
        {
            return ResourceManager.GetString("Filter_AllRisks", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to All baselines.</summary>
    internal static string Filter_AllBaselines
    {
        get
        {
            return ResourceManager.GetString("Filter_AllBaselines", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to Include draft entries.</summary>
    internal static string Category_IncludeDraft
    {
        get
        {
            return ResourceManager.GetString("Category_IncludeDraft", resourceCulture);
        }
    }

    /// <summary>Looks up a localized string similar to {0} of {1} selected.</summary>
    internal static string Category_SelectedCount
    {
        get
        {
            return ResourceManager.GetString("Category_SelectedCount", resourceCulture);
        }
    }
}
